config:
  Train:
    Dataset:
      images_path: ./
      target_col: label
      target_height: 320
      target_width: 320
    loader:
      batch_size: 16
      num_workers: 4
      shuffle: true
  Val:
    Dataset:
      images_path: ./
      target_col: label
      target_height: 320
      target_width: 320
    loader:
      batch_size: 20
      num_workers: 4
      shuffle: false
  logger_path:
    lightning_logger: ./lightning_logs
    main_logger: ./lightning_logs/main_logs.txt
  model_params:
    dropout_p: 0.5
    freeze_bn: false
    model_name: efficientnet_b2b
    num_outputs: 1
    pretrained: true
    show_model_summary: false
  test_inference:
    Dataset:
      images_path: ./
      target_height: 320
      target_width: 320
    TTA:
    - null
    - flip_lr
    - flip_ud
    folds_path: ./lightning_logs/all_train.csv
    loader:
      batch_size: 16
      num_workers: 8
      shuffle: false
    models_path: ./lightning_logs/models
    nfolds: 2
    target_col: label
    threshold: 0.485
    train_csv: all_train.csv
  total_seed: 42
  training:
    ModelCheckpoint:
      kwargs:
        mode: max
        monitor: avg_val_metric
      path: /{epoch:02d}-{avg_val_metric:.4f}
    Trainer:
      accumulate_grad_batches: 1
      auto_lr_find: false
      fast_dev_run: false
      gpus: 1
      max_epochs: 20
      min_epochs: 3
      num_nodes: 1
      precision: 32
      show_progress_bar: false
      train_percent_check: 1
      val_percent_check: 1
    batch_size: 16
    early_stop_callback:
      mode: max
      monitor: acc_metric
      patience: 4
      verbose: true
    loss: FocalLoss
    optimizer:
      kwargs:
        lr: 0.0001
      name: Adam
    scheduler:
      ReduceLROnPlateau:
        factor: 0.5
        mode: max
        patience: 2
        verbose: true
      kwargs:
        frequency: 1
        interval: epoch
        monitor: avg_val_metric
    warmup_steps: 300
  validation:
    batch_size: 16
    folds_path: ./lightning_logs/folds.csv
    location_col: {}
    nfolds: 4
    seed: 42
    target_col: label
    test_csv: None
    train_csv: all_train.csv
